CREATE TABLE REQUEST_COUNTER (
 ID BIGINT PRIMARY KEY auto_increment,
 CURRENCY_ID BIGINT NOT NULL,
 IS_SUCCESS BOOLEAN,
 CREATED_AT TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE CURRENCY (
  ID BIGINT PRIMARY KEY auto_increment,
  CODE varchar(20) NOT NULL
);